mysite1/myapp1/urls.py
from django.urls import path
from .views import create_contact, contact_list, contact_detail, update_contact, delete_contact, home, success, dateerror

app_name = 'myapp1'

urlpatterns = [
    path('success/', success, name='success'),
    path('dateerror/', dateerror, name='dateerror'),
    path('contact/', contact_list, name='contact_list'),
    path('contact/<int:pk>/', contact_detail, name='contact_detail'),
    path('contact/<int:pk>/update/', update_contact, name='update_contact'),
    path('contact/<int:pk>/delete/', delete_contact, name='delete_contact'), 
    path('create/', create_contact, name='create_contact'),
    path('', home, name='home')
]

mysite1/mysite1/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('myapp1/', include('myapp1.urls', namespace='myapp1')),  # Include with the namespace
    path('admin/', admin.site.urls),
]

mysite1/myapp1/models.py
from django.db import models

# Create your models here.

class ContactList(models.Model):
    id =  models.IntegerField(default=0, primary_key= True)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    profession = models.CharField(max_length=200)
    telephone = models.IntegerField(default=0)
    email = models.CharField(max_length=200)
    birthday = models.DateTimeField()

mysite1/myapp1/forms.py
from django import forms
class CreateContactForm(forms.Form):
 formID = forms.IntegerField(label='ID')
 name = forms.CharField(label='Name')
 gender = forms.CharField(label='Gender')
 address = forms.CharField(label='Address')
 profession = forms.CharField(label='Profession')
 telephone = forms.IntegerField(label='Telephone')
 email = forms.CharField(label='Email')
 birthday = forms.DateTimeField(label='Birthday')

mysite1/myapp1/views.py
from .forms import CreateContactForm
from .models import ContactList
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from datetime import date
#from dateutil.relativedelta import relativedelta


#Create your views here.


def home(request):
    return render(request, 'myapp1/home.html')
    
    
def create_contact(request):
    if request.method == 'POST':
        form = CreateContactForm(request.POST)
        if form.is_valid():
            formdata = form.cleaned_data
            formID = formdata['formID']
            name = formdata['name']
            gender = formdata['gender']
            address = formdata['address']
            profession = formdata['profession']
            telephone = formdata['telephone']
            email = formdata['email']
            birthday = formdata['birthday']

            ContactList.objects.create(id=formID, name=name, gender=gender, address=address, profession=profession, telephone=telephone, email=email, birthday=birthday)
            return HttpResponseRedirect('/myapp1/success')
    else:
        form = CreateContactForm()
    return render(request, 'myapp1/create_contact.html', {'form': form})
    
    
def contact_list(request):
    contact_lists = ContactList.objects.all()
    return render(request, 'myapp1/contact_list.html', {'contact_lists': contact_lists})

def contact_detail(request, pk):
    contact = get_object_or_404(ContactList, pk=pk)
    return render(request, 'myapp1/contact_detail.html', {'contact': contact})

def update_contact(request, pk):
    contact = get_object_or_404(ContactList, pk=pk)
    
    if request.method == 'POST':
        form = CreateContactForm(request.POST)
        if form.is_valid():
            # Update the fields of the contact instance with the form data
            contact.name = form.cleaned_data['name']
            contact.gender = form.cleaned_data['gender']
            contact.address = form.cleaned_data['address']
            contact.profession = form.cleaned_data['profession']
            contact.telephone = form.cleaned_data['telephone']
            contact.email = form.cleaned_data['email']
            contact.birthday = form.cleaned_data['birthday']
            
            contact.save()
            
            return redirect('myapp1:success') 
    else:
        # Populate the form fields with the existing data
        form = CreateContactForm(initial={
            'name': contact.name,
            'gender': contact.gender,
            'address': contact.address,
            'profession': contact.profession,
            'telephone': contact.telephone,
            'email': contact.email,
            'birthday': contact.birthday,
        })
    
    return render(request, 'myapp1/update_contact.html', {'form': form})

# Delete operation
def delete_contact(request, pk):
    contact = get_object_or_404(ContactList, pk=pk)
    current_date = date.today()
    eighteenyearsago = current_date - relativedelta(years= 18)
    if request.method == 'POST':
        if contact.birthday.date() >= eighteenyearsago:
            return redirect('myapp1:dateerror')
        else:
            contact.delete()
            return redirect('myapp1:home')
    return render(request, 'myapp1/delete_contact.html', {'contact': contact})
    
def success(request):
 return render(request, 'myapp1/success.html')


def dateerror(request):
 return render(request, 'myapp1/dateerror.html')

mysite1/myapp1/templates/myapp1/contact_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact Details</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Contact Details</h1>
    <p>Name: {{ contact.name }}</p>
    <p>Gender: {{ contact.gender }}</p>
    <p>Address: {{ contact.address }}</p>
    <p>Profession: {{ contact.profession }}</p>
    <p>Telephone: {{ contact.telephone }}</p>
    <p>Email: {{ contact.email }}</p>
	<p>Birthday: {{ contact.birthday }}</p>
    <a href="{% url 'myapp1:update_contact' contact.pk %}" class="submit-button">Edit</a>
    <a href="{% url 'myapp1:delete_contact' contact.pk %}" class="submit-button">Delete</a>
	<a href="{% url 'myapp1:contact_list' %}" class="submit-button">Back</a>
</body>
</html>

mysite1/myapp1/templates/myapp1/contact_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact Lists</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Contact Lists</h1>
    <ul>
        {% for contact in contact_lists %}
            <li>
                    <div style="width: 100%; display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #ccc;">
                        <span style="flex: 1;">
                            <a href="{% url 'myapp1:contact_detail' contact.pk %}" class="view-link">{{ contact.name }}</a>
                        </span>
                        <span style="white-space: nowrap;">
                            <a href="{% url 'myapp1:update_contact' contact.pk %}" style="background-color: #007bff; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; text-decoration: none; font-weight: bold; margin-right: 10px;">Edit</a>
                            <a href="{% url 'myapp1:delete_contact' contact.pk %}" style="background-color: #007bff; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; text-decoration: none; font-weight: bold;">Delete</a>
                        </span>
                    </div>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'myapp1:home' %}" class="submit-button">Home</a>
</body>
</html>

mysite1/myapp1/templates/myapp1/create_contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Form Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        form {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        input[type="text"]{
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;

        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <h1>Contact Form</h1>
    <label for="formID">ID:</label>
    {{ form.formID }}
    
    <label for="name">Name:</label>
    {{ form.name }}
    
    <label for="gender">Gender:</label>
    {{ form.gender }}
    
    <label for="address">Address:</label>
    {{ form.address }}
    
    <label for="profession">Profession:</label>
    {{ form.profession }}
    
    <label for="telephone">Telephone:</label>
    {{ form.telephone }}
    
    <label for="email">Email:</label>
    {{ form.email }}
	
    <label for="birthday">Birthday:</label>
    {{ form.birthday }}
    
    <input type="submit" value="Submit">
</form>
</body>
</html>

mysite1/myapp1/templates/myapp1/dateerror.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Date Error!</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Error!</h1>
    <p>You cannot delete this contact, as they are less than eighteen years old.</p>
    <p><a href="{% url 'myapp1:home' %}" class="submit-button">Back to Home</a></p>
</body>
</html>

mysite1/myapp1/templates/myapp1/delete_contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Contact</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Delete Contact</h1>
    <p>Are you sure you want to delete "{{ contact.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete it">
    </form>
    <a href="{% url 'myapp1:contact_list' %}" class="submit-button">Cancel</a>
</body>
</html>

mysite1/myapp1/templates/myapp1/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact Lists</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Contact Lists</h1>
    <a href="{% url 'myapp1:create_contact' %}" class="home-button">Add New Contact</a>
    <a href="{% url 'myapp1:contact_list' %}" class="home-button">View Current Contacts</a>
</body>
</html>

mysite1/myapp1/templates/myapp1/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Success!</h1>
    <p>Your contact form has been submitted successfully.</p>
    <p><a href="{% url 'myapp1:home' %}" class="submit-button">Back to Home</a></p>
</body>
</html>

mysite1/myapp1/templates/myapp1/update_contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Contact</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body class="container">
    <h1>Edit Contact</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
	<a href="{% url 'myapp1:contact_list' %}" class="submit-button">Back</a>
</body>
</html>